# Funky lil' program that converts the tables in the HL7 spec into my custom JSON format.
# Obviously, this is an imperfect approach that requires double-checking, but it can save an hour of work even on a modestly sized segment.

import json
import math
import pandas as pd
import sys

prefix = None
if len(sys.argv) == 1:
	print("Specify the common prefix for the 'from' fields of all constituents as a command-line arg and their indices will be autogenerated liker '3.2.4.' -> '3.2.4.1', '3.2.4.2', etc.")
	print("python autoconstruct.py [from prefix]")
else:
	prefix = sys.argv[1]

with open("target.xml", "r") as fin:
	# Read the HTML table into a pandas DataFrame
	# Converts the table to a list of dictionaries.
	df = pd.read_html(fin, converters={"TBL#": lambda a : a})[0]
	fields = df.to_dict(orient='records')

#print(json.dumps(fields, indent=2))

constituents = []
for record in fields:
	new_field = {}
	
	if "ELEMENT NAME" in record:
		new_field["description"] = record["ELEMENT NAME"]
	
	if prefix is not None:
		new_field["from"] = prefix + str(len(constituents) + 1)
	
	if "DT" in record:
		new_field["type"] = record["DT"]
		
	if "LEN" in record:
		new_field["length"] = record["LEN"]
	
	if "OPT" in record:
		new_field["optionality"] = record["OPT"]
	
	if "RP/#" in record and (not isinstance(record["RP/#"], float) or not math.isnan(record["RP/#"])):
		if record["RP/#"] == "Y":
			new_field["repeatability"] = -1
		else:
			try:
				new_field["repeatability"] = int(record["RP/#"])
			except:
				pass
	
	if "TBL#" in record and (not isinstance(record["TBL#"], float) or not math.isnan(record["TBL#"])):
		new_field["table"] = record["TBL#"]
	
	constituents.append(new_field)

HL7GR = {
	"SEGMENT type_id": {
		"description": "",
		"long-description": "",
		"from": "",
		"constituents": constituents
	}
}

with open("out.json", "w") as fin:
	fin.write(json.dumps(HL7GR, indent=2))